Fix CI/CD workflow with docker api test

diff --git a/.github/workflows/ml_pipeline.yml b/.github/workflows/ml_pipeline.yml
--- a/.github/workflows/ml_pipeline.yml
+++ b/.github/workflows/ml_pipeline.yml
@@ -39,14 +39,12 @@ jobs:
         run: |
           docker run -d -p 8001:8001 --name test-api sales-forcast-api:ci
           sleep 5
-          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST http://localhost:8001/predict \
-           -H "Content-Type: application/json" \
-           -d '{"data":[{"Store":1,"DayOfWeek":5,"Open":1,"Promo":0}]}')
+          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST http://localhost:8001/predict -H "Content-Type: application/json" -d '{"data":[{"Store":1,"DayOfWeek":5,"Open":1,"Promo":0}]}')
           docker stop test-api
-          if [ "$RESPONSE" -ne 200 ]; then
-           echo "API test failed!"
-           exit 1
-
+          echo "Response code: $RESPONSE"
+          if [ "$RESPONSE" != "200" ]; then
+            echo "API test failed!"
+            exit 1
       - name: Push Docker image
         run: |
           docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
