Fix CI/CD workflow with docker api test

diff --git a/.github/workflows/ml_pipeline.yml b/.github/workflows/ml_pipeline.yml
--- a/.github/workflows/ml_pipeline.yml
+++ b/.github/workflows/ml_pipeline.yml
@@ -28,18 +28,27 @@ jobs:
 
       - name: Run Tests
         run: |
-          pytest tests/
+          pytest tests/ --maxfail=1 --disable-warnings
 
       - name: Build Docker Image
         run: |
-          docker build -t sales-forecast-api .
+          docker build -t sales-forecast-api:ci .
 
-      # Optional: skip for now, can test locally later
-      #- name: Run Docker container
-      #  run: |
-      #    docker run -d -p 8001:8001 --name test-api sales-forecast-api
-      #    sleep 5
-      #    curl -X POST http://localhost:8001/predict \
-      #      -H "Content-Type: application/json" \
-      #      -d '{"data":[{"Store":1,"DayOfWeek":5,"Open":1,"Promo":0,"StateHoliday":"0","SchoolHoliday":0}]}'
-      #    docker stop test-api
+
+      -name: Test Docker container
+       run: |
+         docker run -d -p 8001:8001 --name test-api sales-forcast-api:ci
+         sleep 5 
+          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST http://localhost:8001/predict \
+            -H "Content-Type: application/json" \
+            -d '{"data":[{"Store":1,"DayOfWeek":5,"Open":1,"Promo":0}]}')
+          docker stop test-api
+          if [ "$RESPONSE" -ne 200 ]; then
+            echo "API test failed!"
+            exit 1
+            
+      - name: Push Docker image
+        run: |
+          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
+          docker tag sales-forecast-api:ci your-dockerhub-username/sales-forecast-api:latest
+          docker push your-dockerhub-username/sales-forecast-api:latest
